import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Feature-Anfragen',
  filterNew: 'Neu',
  filterPlanned: 'Geplant',
  filterInProgress: 'In Arbeit',
  filterDone: 'Fertig',
  titlePlaceholder: 'Feature-Titel',
  descriptionPlaceholder: 'Beschreibe das Feature...',
  submit: 'Absenden',
  cancel: 'Abbrechen',
  back: 'Zurück',
  close: 'Schließen',
  emailPlaceholder: 'Deine E-Mail-Adresse',
  emailEncouragement: 'Gib deine E-Mail an, damit wir dir antworten können',
  emailRequired: 'E-Mail ist erforderlich',
  emailSkipTitle: 'Ohne E-Mail absenden?',
  emailSkipMessage: 'Du hast keine E-Mail eingegeben. Wir können dir nicht antworten.',
  emailSkipConfirm: 'Trotzdem absenden',
  emailInvalid: 'Bitte gib eine gültige E-Mail-Adresse ein',
  empty: 'Noch keine Feature-Anfragen',
  emptyHint: 'Sei der Erste, der ein Feature vorschlägt!',
  error: 'Etwas ist schiefgelaufen',
  mutationError: 'Die Änderung konnte nicht gespeichert werden. Bitte prüfe deine Verbindung und versuche es erneut.',
  retry: 'Erneut versuchen',
  comments: 'Kommentare',
  commentsCount: '{count} Kommentare',
  noComments: 'Noch keine Kommentare',
  noCommentsHint: 'Sei der Erste, der seine Meinung teilt',
  commentPlaceholder: 'Kommentar schreiben...',
  postComment: 'Senden',
  developerBadge: 'Entwickler',
  youBadge: 'Du',
  userBadge: 'Nutzer',
  voteComment: 'Kommentar positiv bewerten',
  pendingReview: 'Ausstehende Pr\u00fcfung',
  badgePlanned: 'Geplant',
  badgeDeclined: 'Abgelehnt',
  newRequest: 'Neue Anfrage',
};
