import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Solicitudes de funciones',
  filterNew: 'Nuevo',
  filterPlanned: 'Planificado',
  filterInProgress: 'En progreso',
  filterDone: 'Hecho',
  titlePlaceholder: 'Título de la función',
  descriptionPlaceholder: 'Describe la función...',
  submit: 'Enviar',
  cancel: 'Cancelar',
  back: 'Volver',
  close: 'Cerrar',
  emailPlaceholder: 'Tu correo electrónico',
  emailEncouragement: 'Añade tu correo para que podamos contactarte',
  emailRequired: 'El correo es obligatorio',
  emailSkipTitle: '¿Enviar sin correo electrónico?',
  emailSkipMessage: 'No has introducido un correo electrónico. No podremos contactarte.',
  emailSkipConfirm: 'Enviar de todos modos',
  emailInvalid: 'Introduce una dirección de correo válida',
  empty: 'Aún no hay solicitudes',
  emptyHint: '¡Sé el primero en sugerir una función!',
  error: 'Algo salió mal',
  mutationError: 'No se pudo guardar el cambio. Comprueba tu conexión e inténtalo de nuevo.',
  retry: 'Reintentar',
  comments: 'Comentarios',
  commentsCount: '{count} comentarios',
  noComments: 'Aún no hay comentarios',
  noCommentsHint: 'Sé el primero en compartir tu opinión',
  commentPlaceholder: 'Escribe un comentario...',
  postComment: 'Publicar',
  developerBadge: 'Desarrollador',
  youBadge: 'Tú',
  userBadge: 'Usuario',
  voteComment: 'Votar por comentario',
  pendingReview: 'Pendiente de revisi\u00f3n',
  badgePlanned: 'Planificado',
  badgeDeclined: 'Rechazado',
  newRequest: 'Nueva solicitud',
};
