import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Demandes de fonctionnalités',
  filterNew: 'Nouveau',
  filterPlanned: 'Planifié',
  filterInProgress: 'En cours',
  filterDone: 'Terminé',
  titlePlaceholder: 'Titre de la fonctionnalité',
  descriptionPlaceholder: 'Décrivez la fonctionnalité...',
  submit: 'Envoyer',
  cancel: 'Annuler',
  emailPlaceholder: 'Votre adresse e-mail',
  emailEncouragement: 'Ajoutez votre e-mail pour que nous puissions vous répondre',
  emailRequired: 'L\'e-mail est requis',
  emailSkipTitle: 'Envoyer sans e-mail ?',
  emailSkipMessage: 'Vous n\'avez pas saisi d\'e-mail. Nous ne pourrons pas vous recontacter.',
  emailSkipConfirm: 'Envoyer quand même',
  emailInvalid: 'Veuillez saisir une adresse e-mail valide',
  empty: 'Aucune demande pour le moment',
  emptyHint: 'Soyez le premier à proposer une fonctionnalité !',
  error: 'Une erreur est survenue',
  retry: 'Réessayer',
  comments: 'Commentaires',
  commentsCount: '{count} commentaires',
  noComments: 'Pas encore de commentaires',
  noCommentsHint: 'Soyez le premier à partager votre avis',
  commentPlaceholder: 'Écrire un commentaire...',
  postComment: 'Publier',
  developerBadge: 'Développeur',
  pendingReview: 'En attente de validation',
  badgePlanned: 'Planifié',
  newRequest: 'Nouvelle demande',
};
