import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: '機能リクエスト',
  filterNew: '新規',
  filterPlanned: '計画中',
  filterInProgress: '進行中',
  filterDone: '完了',
  titlePlaceholder: '機能のタイトル',
  descriptionPlaceholder: '機能の説明...',
  submit: '送信',
  cancel: 'キャンセル',
  emailPlaceholder: 'メールアドレス',
  emailEncouragement: 'フォローアップのためメールアドレスを入力してください',
  emailRequired: 'メールアドレスは必須です',
  emailSkipTitle: 'メールなしで送信しますか？',
  emailSkipMessage: 'メールアドレスが入力されていません。返信できなくなります。',
  emailSkipConfirm: 'そのまま送信',
  emailInvalid: '有効なメールアドレスを入力してください',
  empty: 'まだリクエストはありません',
  emptyHint: '最初の機能を提案しましょう！',
  error: 'エラーが発生しました',
  retry: '再試行',
  comments: 'コメント',
  commentsCount: '{count}件のコメント',
  noComments: 'まだコメントはありません',
  noCommentsHint: '最初にコメントしてみましょう',
  commentPlaceholder: 'コメントを入力...',
  postComment: '投稿',
  developerBadge: '開発者',
  pendingReview: 'レビュー待ち',
  badgePlanned: '計画中',
  newRequest: '新規リクエスト',
};
