import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: '기능 요청',
  filterNew: '신규',
  filterPlanned: '계획됨',
  filterInProgress: '진행 중',
  filterDone: '완료',
  titlePlaceholder: '기능 제목',
  descriptionPlaceholder: '기능을 설명해 주세요...',
  submit: '제출',
  cancel: '취소',
  emailPlaceholder: '이메일 주소',
  emailEncouragement: '후속 연락을 위해 이메일을 입력해 주세요',
  emailRequired: '이메일은 필수입니다',
  emailSkipTitle: '이메일 없이 제출하시겠습니까?',
  emailSkipMessage: '이메일을 입력하지 않았습니다. 회신할 수 없습니다.',
  emailSkipConfirm: '그래도 제출',
  emailInvalid: '유효한 이메일 주소를 입력해주세요',
  empty: '아직 요청이 없습니다',
  emptyHint: '첫 번째로 기능을 제안해 보세요!',
  error: '문제가 발생했습니다',
  retry: '다시 시도',
  comments: '댓글',
  commentsCount: '댓글 {count}개',
  noComments: '아직 댓글이 없습니다',
  noCommentsHint: '첫 번째로 의견을 남겨보세요',
  commentPlaceholder: '댓글을 입력하세요...',
  postComment: '게시',
  developerBadge: '개발자',
  pendingReview: '검토 대기중',
  badgePlanned: '계획됨',
  newRequest: '새 요청',
};
