import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Functieverzoeken',
  filterNew: 'Nieuw',
  filterPlanned: 'Gepland',
  filterInProgress: 'In uitvoering',
  filterDone: 'Voltooid',
  titlePlaceholder: 'Functietitel',
  descriptionPlaceholder: 'Beschrijf de functie...',
  submit: 'Verzenden',
  cancel: 'Annuleren',
  back: 'Terug',
  close: 'Sluiten',
  emailPlaceholder: 'Je e-mailadres',
  emailEncouragement: 'Voeg je e-mail toe zodat we je kunnen bereiken',
  emailRequired: 'E-mail is verplicht',
  emailSkipTitle: 'Verzenden zonder e-mail?',
  emailSkipMessage: 'Je hebt geen e-mailadres ingevuld. We kunnen geen contact met je opnemen.',
  emailSkipConfirm: 'Toch verzenden',
  emailInvalid: 'Voer een geldig e-mailadres in',
  empty: 'Nog geen functieverzoeken',
  emptyHint: 'Wees de eerste die een functie voorstelt!',
  error: 'Er is iets misgegaan',
  mutationError: 'De wijziging kon niet worden opgeslagen. Controleer je verbinding en probeer het opnieuw.',
  retry: 'Opnieuw proberen',
  comments: 'Reacties',
  commentsCount: '{count} reacties',
  noComments: 'Nog geen reacties',
  noCommentsHint: 'Wees de eerste die reageert',
  commentPlaceholder: 'Schrijf een reactie...',
  postComment: 'Plaatsen',
  developerBadge: 'Ontwikkelaar',
  youBadge: 'Jij',
  userBadge: 'Gebruiker',
  voteComment: 'Stem op reactie',
  pendingReview: 'Wacht op beoordeling',
  badgePlanned: 'Gepland',
  badgeDeclined: 'Afgewezen',
  newRequest: 'Nieuw verzoek',
};
