import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Propozycje funkcji',
  filterNew: 'Nowe',
  filterPlanned: 'Planowane',
  filterInProgress: 'W toku',
  filterDone: 'Gotowe',
  titlePlaceholder: 'Tytuł funkcji',
  descriptionPlaceholder: 'Opisz funkcję...',
  submit: 'Wyślij',
  cancel: 'Anuluj',
  emailPlaceholder: 'Twój adres e-mail',
  emailEncouragement: 'Dodaj swój e-mail, abyśmy mogli się z Tobą skontaktować',
  emailRequired: 'E-mail jest wymagany',
  emailSkipTitle: 'Wyślij bez e-maila?',
  emailSkipMessage: 'Nie podano adresu e-mail. Nie będziemy mogli się z Tobą skontaktować.',
  emailSkipConfirm: 'Wyślij mimo to',
  emailInvalid: 'Podaj prawidłowy adres e-mail',
  empty: 'Brak propozycji',
  emptyHint: 'Bądź pierwszy i zaproponuj funkcję!',
  error: 'Coś poszło nie tak',
  retry: 'Spróbuj ponownie',
  comments: 'Komentarze',
  commentsCount: '{count} komentarzy',
  noComments: 'Brak komentarzy',
  noCommentsHint: 'Bądź pierwszy i podziel się swoją opinią',
  commentPlaceholder: 'Napisz komentarz...',
  postComment: 'Opublikuj',
  developerBadge: 'Deweloper',
  pendingReview: 'Oczekuje na sprawdzenie',
  badgePlanned: 'Planowane',
  newRequest: 'Nowa propozycja',
};
