import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: 'Pedidos de funcionalidades',
  filterNew: 'Novo',
  filterPlanned: 'Planeado',
  filterInProgress: 'Em progresso',
  filterDone: 'Concluído',
  titlePlaceholder: 'Título da funcionalidade',
  descriptionPlaceholder: 'Descreva a funcionalidade...',
  submit: 'Enviar',
  cancel: 'Cancelar',
  emailPlaceholder: 'Seu endereço de e-mail',
  emailEncouragement: 'Adicione seu e-mail para que possamos entrar em contato',
  emailRequired: 'E-mail é obrigatório',
  emailSkipTitle: 'Enviar sem e-mail?',
  emailSkipMessage: 'Você não inseriu um e-mail. Não poderemos entrar em contato.',
  emailSkipConfirm: 'Enviar mesmo assim',
  emailInvalid: 'Insira um endereço de e-mail válido',
  empty: 'Ainda não há pedidos',
  emptyHint: 'Seja o primeiro a sugerir uma funcionalidade!',
  error: 'Algo correu mal',
  retry: 'Tentar novamente',
  comments: 'Comentários',
  commentsCount: '{count} comentários',
  noComments: 'Ainda não há comentários',
  noCommentsHint: 'Seja o primeiro a compartilhar sua opinião',
  commentPlaceholder: 'Escreva um comentário...',
  postComment: 'Publicar',
  developerBadge: 'Desenvolvedor',
  pendingReview: 'Pendente de revis\u00e3o',
  badgePlanned: 'Planeado',
  newRequest: 'Novo pedido',
};
