import type { FeaturamaStrings } from './en';

export const strings: FeaturamaStrings = {
  title: '功能请求',
  filterNew: '新建',
  filterPlanned: '已计划',
  filterInProgress: '进行中',
  filterDone: '已完成',
  titlePlaceholder: '功能标题',
  descriptionPlaceholder: '描述该功能...',
  submit: '提交',
  cancel: '取消',
  emailPlaceholder: '您的电子邮箱',
  emailEncouragement: '添加您的邮箱以便我们与您联系',
  emailRequired: '电子邮箱为必填项',
  emailSkipTitle: '不填邮箱直接提交？',
  emailSkipMessage: '您未输入邮箱地址，我们将无法与您联系。',
  emailSkipConfirm: '仍然提交',
  emailInvalid: '请输入有效的邮箱地址',
  empty: '暂无功能请求',
  emptyHint: '成为第一个提出功能建议的人！',
  error: '出了点问题',
  retry: '重试',
  comments: '评论',
  commentsCount: '{count} 条评论',
  noComments: '暂无评论',
  noCommentsHint: '成为第一个发表评论的人',
  commentPlaceholder: '写下评论...',
  postComment: '发表',
  developerBadge: '开发者',
  pendingReview: '待审核',
  badgePlanned: '已计划',
  newRequest: '新请求',
};
